name: Backend CI

on:
  push:
    paths:
      - API/**
  pull_request:
    branches: [ "dev" , "Master"]
defaults:
  run:
    working-directory: API

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

