name: React Build and Test

on:
  push:
    paths:
      - React/**
  pull_request:
    branches: [ "dev","Master" ]
defaults:
  run:
    working-directory: React
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      - name: Build Vite 
        run: vite build
      - name: Build the React application
        run: npm run build --if-present

